/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Diablo)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x801C8C04u
#define func_801C8C04 BootEntry  /* alias */
